# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Layers" do
  pod 'AsyncDisplayKit', :git => 'git@github.com:facebook/AsyncDisplayKit.git'
end

target "LayersTests" do

end

