//
//  RainforestLifeform.swift
//  Layers
//
//  Created by René Cacheaux on 9/21/14.
//  Copyright (c) 2014 Razeware LLC. All rights reserved.
//

struct RainforestLifeform {
  let name: String
  let description: String
  let imageName: String
}

func allLifeforms() -> [RainforestLifeform] {
  return [
    RainforestLifeform(name: "Harpy Eagle", description: "The harpy eagle (Harpia harpyja) is a Neotropical species of eagle. It is sometimes known as the American harpy eagle to distinguish it from the Papuan eagle which is sometimes known as the New Guinea harpy eagle or Papuan harpy eagle.[3] It is the largest and most powerful raptor found in the Americas,[4] and among the largest extant species of eagles in the world.", imageName: "a01"),
    RainforestLifeform(name: "Chameleon", description: "Chameleons or chamaeleons (family Chamaeleonidae) are a distinctive and highly specialized clade of lizards. The approximately 160 species of chameleon come in a range of colors, and many species have the ability to change colors. Chameleons are distinguished by their zygodactylous feet; their very long, highly modified, rapidly extrudable tongues;", imageName: "a02"),
    RainforestLifeform(name: "Blue Morpho", description: "The Menelaus Blue Morpho (Morpho menelaus) is an iridescent tropical butterfly of Central and South America. It has a wing span of 15 cm (5.9 in). The adult drinks juice from rotten fruit with its long proboscis, which is like a sucking tube. The adult males have brighter colours than the females.", imageName: "a03"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap.", imageName: "a04"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a05"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a06"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a07"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a08"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a09"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a10"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a11"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a12"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a13"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a14"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a15"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a16"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a17"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a18"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a19"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a20"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a21"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a22"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a23"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a24"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a25"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a26"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a27"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a28"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a29"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a30"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a31"),
    RainforestLifeform(name: "Fill In", description: "Polaroid heirloom pork belly keffiyeh tousled, master cleanse church-key Godard artisan swag shabby chic Truffaut. Freegan mlkshk fap meh, pickled typewriter messenger bag Portland small batch. Pork belly keytar cliche, twee artisan literally asymmetrical fingerstache fap. Pinterest quinoa next level heirloom synth, Blue Bottle authentic twee. Viral whatever sustainable synth, mlkshk small batch trust fund you probably haven't heard of them. Marfa High Life stumptown, mlkshk banjo Tonx tote bag irony mixtape Odd Future 3 wolf moon cray fap. Drinking vinegar heirloom hella, raw denim aesthetic mlkshk crucifix four loko 90's ugh synth Intelligentsia lomo normcore.", imageName: "a32")
  ]
}